# Generated by Django 4.1.4 on 2022-12-26 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QonGuruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='QonOluvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
                ('vil', models.CharField(blank=True, max_length=200)),
                ('tuman', models.CharField(blank=True, max_length=300)),
                ('manzil', models.CharField(blank=True, max_length=500)),
                ('sana', models.DateTimeField(auto_now=True)),
                ('qon_guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.qonguruh')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_sana', models.DateField(blank=True)),
                ('tel', models.CharField(max_length=20)),
                ('vil', models.CharField(max_length=100)),
                ('tuman', models.CharField(max_length=100)),
                ('manzil', models.TextField(blank=True, max_length=500)),
                ('jins', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=10)),
                ('rasm', models.ImageField(upload_to='')),
                ('topshirishga_tayyor', models.BooleanField(default=True)),
                ('donor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qon_guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.qonguruh')),
            ],
        ),
    ]
