# Generated by Django 4.1.4 on 2022-12-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='rasm',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
